language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
install:
 - sudo pip install -r requirements.txt
script:
 - pep8 googlegeocoder
 - pyflakes googlegeocoder
 - coverage run test.py
after_success:
 - coveralls
